version: '3'
services:
  web:
    image: 'cypress/included:cypress-12.4.1-node-16.18.1-chrome-109.0.5414.74-1-ff-109.0-edge-109.0.1518.52-1'
    container_name: webapp-frontend
    ports:
      - '5000:5000'
    volumes:
      - .:/opt/app
    working_dir: '/opt/app'
    entrypoint: /bin/sh
    command:
      ['-c', 'npm install && ./node_modules/.bin/nx run react-app-e2e:e2e']
    depends_on:
      - backend
  backend:
    image: 'node:18'
    container_name: node-backend
    volumes:
      - .:/opt/app
    working_dir: '/opt/app'
    command: 'node ./apps/simple-node-backend/app.js'
